### ISSUE TITLE
i am paul petscop yes

### ISSUE THREAD

**Issue by danielh05** [BubbleDerp/Petscop3D-Source#1]
yes i am totally paul petscop and i will have to take this down for being ilelgalgkogzwesijporwhsw
how do i spell ilegel fuck aijgeszijohdsijogdesitgdesgs
help uionhgrsgrwspo
illiegel
YOU FAKtgzesi0oz0esijpofhdfrhd
help

**Comment by HectyHector** [comment]
closing issue due to not being related at all to code lol

**Comment by danielh05** [comment]
BUT HOW DO YOU WRITE ILLAGLE

**Comment by Caylie-C** [comment]
Illegal.
